package miage.Crous.Data.Entity;
// Generated 4 nov. 2018 à 15:41:25 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bien generated by hbm2java
 */
@Entity
@Table(name = "BIEN")
public class Bien implements java.io.Serializable {

	/**
	 * Identifiant de la sérialisation.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Identifiant du bien.
	 */
	private Integer idBien;

	/**
	 * Adresse du bien.
	 */
	private String addressB;

	/**
	 * Nature du bien.
	 */
	private int nature;

	/**
	 * Liste propriétaire. 
	 */
	private Set<Possede> possedes = new HashSet<Possede>(0);
	
	/**
	 * Liste des locataire du bien.
	 */
	private Set<Location> locations = new HashSet<Location>(0);
	
	/**
	 * Constructeur de la classe bien.
	 */
	public Bien() {
	}

	/**
	 * Construction d'un bien.
	 * @param addressB address du bien.
	 * @param nature Nature du bien.
	 */
	public Bien(String addressB, int nature) {
		this.addressB = addressB;
		this.nature = nature;
	}
	
	/**
	 *	Contructeur d'un bien. 
	 * @param addressB Adresse du bien.
	 * @param nature Nature du bien.
	 * @param possedes liste propriétaire.
	 * @param locations liste de locataire.
	 */
	public Bien(String addressB, int nature, Set<Possede> possedes, Set<Location> locations) {
		this.addressB = addressB;
		this.nature = nature;
		this.possedes = possedes;
		this.locations = locations;
	}


	/**
	 * Obtient l'identifiant du bien.
	 * @return L'identifiant du bien.
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_bien", unique = true, nullable = false)
	public Integer getIdBien() {
		return this.idBien;
	}

	/**
	 * Permet la mise à jour de l'identifiant du bien.
	 * @param idBien nouvelle id.
	 */
	public void setIdBien(Integer idBien) {
		this.idBien = idBien;
	}

	/**
	 * Obtient l'adresse du bien.
	 * @return L'adresse du bien.
	 */
	@Column(name = "address_b", nullable = false, length = 30)
	public String getAddressB() {
		return this.addressB;
	}

	/**
	 * Permet la mise à jour de l'identifiant du bien.
	 * @param addressB nouvelle adresse.
	 */
	public void setAddressB(String addressB) {
		this.addressB = addressB;
	}

	/**
	 * Obtient la nature.
	 * @return l'id de la nature.
	 */
	@Column(name = "nature", nullable = false)
	public int getNature() {
		return this.nature;
	}

	/**
	 * Permet la mise à jour de la nature.
	 * @param nature
	 */
	public void setNature(int nature) {
		this.nature = nature;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bien")
	public Set<Possede> getPossedes() {
		return this.possedes;
	}

	public void setPossedes(Set<Possede> possedes) {
		this.possedes = possedes;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bien")
	public Set<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<Location> locations) {
		this.locations = locations;
	}
}
