package miage.Crous.Data.Entity;
// Generated 4 nov. 2018 à 15:41:25 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bien generated by hbm2java
 */
@Entity
@Table(name = "BIEN")
public class Bien implements java.io.Serializable {

	/**
	 * Identifiant de la sérialisation.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Identifiant du bien.
	 */
	private Integer idBien;

	/**
	 * Adresse du bien.
	 */
	private String addressB;

	/**
	 * Nature du bien.
	 */
	private int nature;
	
	private Set<Possede> possedes = new HashSet<Possede>(0);
	private Set<Location> locations = new HashSet<Location>(0);
	
	/**
	 * Constructeur de la classe bien.
	 */
	public Bien() {
	}

	/**
	 * 
	 * @param addressB
	 * @param nature
	 */
	public Bien(String addressB, int nature) {
		this.addressB = addressB;
		this.nature = nature;
	}
	
	public Bien(String addressB, int nature, Set<Possede> possedes, Set<Location> locations) {
		this.addressB = addressB;
		this.nature = nature;
		this.possedes = possedes;
		this.locations = locations;
	}


	/**
	 * 
	 * @return
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_bien", unique = true, nullable = false)
	public Integer getIdBien() {
		return this.idBien;
	}

	/**
	 * 
	 * @param idBien
	 */
	public void setIdBien(Integer idBien) {
		this.idBien = idBien;
	}

	/**
	 * 
	 * @return
	 */
	@Column(name = "address_b", nullable = false, length = 30)
	public String getAddressB() {
		return this.addressB;
	}

	/**
	 * 
	 * @param addressB
	 */
	public void setAddressB(String addressB) {
		this.addressB = addressB;
	}

	/**
	 * 
	 * @return
	 */
	@Column(name = "nature", nullable = false)
	public int getNature() {
		return this.nature;
	}

	/**
	 * 
	 * @param nature
	 */
	public void setNature(int nature) {
		this.nature = nature;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bien")
	public Set<Possede> getPossedes() {
		return this.possedes;
	}

	public void setPossedes(Set<Possede> possedes) {
		this.possedes = possedes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bien")
	public Set<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<Location> locations) {
		this.locations = locations;
	}
}
