package miage.Crous.Data.Entity;
// Generated 4 nov. 2018 à 15:41:25 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Possede generated by hbm2java
 */
@Entity
@Table(name = "POSSEDE", catalog = "MIAGE_CROUS")
public class Possede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PossedeId id;
	private Bien bien;
	private Personne personne;

	public Possede() {
	}

	public Possede(PossedeId id, Bien bien, Personne personne) {
		this.id = id;
		this.bien = bien;
		this.personne = personne;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idBien", column = @Column(name = "id_bien", nullable = false)),
			@AttributeOverride(name = "idPersonne", column = @Column(name = "id_personne", nullable = false)) })
	public PossedeId getId() {
		return this.id;
	}

	public void setId(PossedeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bien", nullable = false, insertable = false, updatable = false)
	public Bien getBien() {
		return this.bien;
	}

	public void setBien(Bien bien) {
		this.bien = bien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personne", nullable = false, insertable = false, updatable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

}
