package miage.Crous.Data.Entity;
// Generated 4 nov. 2018 à 15:41:25 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entité des gestions des type;
 * Type generated by hbm2java
 */
@Entity
@Table(name = "TYPE")
public class TypeIndividu implements java.io.Serializable {

	/**
	 * Numéro de version de la classe.
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Identifiant de la table;
	 */
	private Integer idType;
	
	/**
	 * Nom du type.
	 */
	private String nameType;
	
	/**
	 * Liste des personnes dans la catégorie. 
	 */
	private Set<Personne> personnes = new HashSet<Personne>(0);

	/**
	 * Conctructeur par défaut de la classe.
	 */
	public TypeIndividu() {
	}

	/**
	 * Contructeur avec le nom du paramètre.
	 * @param nameType nom du type.
	 */
	public TypeIndividu(String nameType) {
		this.nameType = nameType;
	}

	public TypeIndividu(String nameType, Set<Personne> personnes) {
		this.nameType = nameType;
		this.personnes = personnes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_type", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "name_type", nullable = false, length = 30)
	public String getNameType() {
		return this.nameType;
	}

	public void setNameType(String nameType) {
		this.nameType = nameType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Personne> getPersonnes() {
		return this.personnes;
	}

	public void setPersonnes(Set<Personne> personnes) {
		this.personnes = personnes;
	}

}
